- name: clone repo dotstamp_deploy
  become: false
  git: "repo=git@bitbucket.org:wheatandcat/dotstamp_deploy.git dest=/project/dotstamp_deploy accept_hostkey=true"
  tags:
    - git
    - deploy
- name: project blue directory
  become: true
  file: path=/project/blue state=directory owner=root group=root mode=0777
  tags:
    - deploy
- name: project blue directory tool open-jtalk
  become: true
  file: path=/project/blue/dotstamp_deploy/tool/open-jtalk/voice state=directory owner=root group=root mode=0777
  tags:
    - deploy
- name: make link open jtalk dic
  become: false
  file:
    src: /usr/local/share/open_jtalk/{{open_jtalk_dic_ver}}
    dest: /project/blue/dotstamp_deploy/tool/open-jtalk/dic
    state: link
  tags:
    - deploy
- name: make link open jtalk mei voice
  become: false
  file:
    src: /usr/local/share/hts_voice/mei
    dest: /project/blue/dotstamp_deploy/tool/open-jtalk/voice/mei
    state: link
  tags:
    - deploy
- name: make link open jtalk m100 voice
  become: false
  file:
    src: /usr/local/share/hts_voice/hts_voice_nitech_jp_atr503_m001-1.05/
    dest: /project/blue/dotstamp_deploy/tool/open-jtalk/voice/m100
    state: link
  tags:
    - deploy
- name: project green directory
  become: true
  file: path=/project/green state=directory owner=root group=root mode=0777
  tags:
    - deploy
- name: project green directory tool open-jtalk
  become: true
  file: path=/project/green/dotstamp_deploy/tool/open-jtalk/voice state=directory owner=root group=root mode=0777
  tags:
    - deploy
- name: make link open jtalk dic
  become: false
  file:
    src: /usr/local/share/open_jtalk/{{open_jtalk_dic_ver}}
    dest: /project/green/dotstamp_deploy/tool/open-jtalk/dic
    state: link
  tags:
    - deploy
- name: make link open jtalk mei voice
  become: false
  file:
    src: /usr/local/share/hts_voice/mei
    dest: /project/green/dotstamp_deploy/tool/open-jtalk/voice/mei
    state: link
  tags:
    - deploy
- name: make link open jtalk m100 voice
  become: false
  file:
    src: /usr/local/share/hts_voice/hts_voice_nitech_jp_atr503_m001-1.05/
    dest: /project/green/dotstamp_deploy/tool/open-jtalk/voice/m100
    state: link
  tags:
    - deploy
- name: make deploy shell
  become: true
  template: src=deploy.sh.j2 dest=/root/deploy.sh mode=0700
  tags:
    - deploy
